import { Core } from "stellar-plus/lib/stellar-plus";

export const wasmPath =
  "../../target/wasm32-unknown-unknown/release/counter.wasm";

export enum Methods {
  GetEvenCount = "get_even_count",
  GetOddCount = "get_odd_count",
}

export const spec = new Core.Spec([
  "AAAAAAAAAAAAAAAPcmV2aWV3X3RyYW5zZmVyAAAAAAMAAAAAAAAABV9mcm9tAAAAAAAAEwAAAAAAAAADX3RvAAAAABMAAAAAAAAABmFtb3VudAAAAAAACwAAAAA=",
  "AAAAAAAAAAAAAAAOZ2V0X2V2ZW5fY291bnQAAAAAAAAAAAABAAAABg==",
  "AAAAAAAAAAAAAAANZ2V0X29kZF9jb3VudAAAAAAAAAAAAAABAAAABg==",
  "AAAAAgAAAAAAAAAAAAAAB0RhdGFLZXkAAAAAAgAAAAAAAAAAAAAAA09kZAAAAAAAAAAAAAAAAARFdmVu",
  "AAAAAgAAAAAAAAAAAAAAC01ldGFkYXRha2V5AAAAAAEAAAAAAAAAAAAAAA9XcmFwcGVyTWV0YWRhZGEA",
  "AAAAAQAAAAAAAAAAAAAAD1dyYXBwZXJNZXRhZGF0YQAAAAAFAAAAAAAAAAVhZG1pbgAAAAAAABMAAAAAAAAABWFzc2V0AAAAAAAAEwAAAAAAAAAQYXNzZXRfY29udHJvbGxlcgAAABMAAAAAAAAACGVuZm9yY2VkAAAAAQAAAAAAAAAJaXNfYWN0aXZlAAAAAAAAAQ==",
]);
