import { Core } from "stellar-plus/lib/stellar-plus";

export const wasmPath =
  "../../target/wasm32-unknown-unknown/release/payment.wasm";

export enum Methods {
  Initialize = "initialize",
  Pay = "pay",
}

export const spec = new Core.Spec([
  "AAAAAAAAAAAAAAAKaW5pdGlhbGl6ZQAAAAAAAQAAAAAAAAAFYXNzZXQAAAAAAAATAAAAAA==",
  "AAAAAAAAAAAAAAADcGF5AAAAAAMAAAAAAAAABGZyb20AAAATAAAAAAAAAAJ0bwAAAAAAEwAAAAAAAAAGYW1vdW50AAAAAAALAAAAAA==",
  "AAAAAgAAAAAAAAAAAAAAC01ldGFkYXRha2V5AAAAAAEAAAAAAAAAAAAAAA9XcmFwcGVyTWV0YWRhZGEA",
  "AAAAAQAAAAAAAAAAAAAAD1dyYXBwZXJNZXRhZGF0YQAAAAAFAAAAAAAAAAVhZG1pbgAAAAAAABMAAAAAAAAABWFzc2V0AAAAAAAAEwAAAAAAAAAQYXNzZXRfY29udHJvbGxlcgAAABMAAAAAAAAACGVuZm9yY2VkAAAAAQAAAAAAAAAJaXNfYWN0aXZlAAAAAAAAAQ==",
]);
