import { Core } from "stellar-plus/lib/stellar-plus";

export const wasmPath =
  "../../target/wasm32-unknown-unknown/release/optional_classic_asset_wrapper.wasm";

export enum Methods {
  Initialize = "initialize",
  IsWrapperActive = "is_wrapper_active",
  GetMetadata = "get_metadata",
  Transfer = "transfer",
}

export const spec = new Core.Spec([
  "AAAAAAAAAAAAAAAIdHJhbnNmZXIAAAADAAAAAAAAAARmcm9tAAAAEwAAAAAAAAACdG8AAAAAABMAAAAAAAAABmFtb3VudAAAAAAACwAAAAA=",
  "AAAAAAAAAAAAAAAMZ2V0X21ldGFkYXRhAAAAAAAAAAEAAAfQAAAAD1dyYXBwZXJNZXRhZGF0YQA=",
  "AAAAAAAAAAAAAAARaXNfd3JhcHBlcl9hY3RpdmUAAAAAAAAAAAAAAQAAAAE=",
  "AAAAAAAAAAAAAAAKaW5pdGlhbGl6ZQAAAAAAAwAAAAAAAAAFYWRtaW4AAAAAAAATAAAAAAAAAAVhc3NldAAAAAAAABMAAAAAAAAAEGFzc2V0X2NvbnRyb2xsZXIAAAATAAAAAA==",
  "AAAAAgAAAAAAAAAAAAAAC01ldGFkYXRha2V5AAAAAAEAAAAAAAAAAAAAAA9XcmFwcGVyTWV0YWRhZGEA",
  "AAAAAQAAAAAAAAAAAAAAD1dyYXBwZXJNZXRhZGF0YQAAAAAFAAAAAAAAAAVhZG1pbgAAAAAAABMAAAAAAAAABWFzc2V0AAAAAAAAEwAAAAAAAAAQYXNzZXRfY29udHJvbGxlcgAAABMAAAAAAAAACGVuZm9yY2VkAAAAAQAAAAAAAAAJaXNfYWN0aXZlAAAAAAAAAQ==",
]);
